# Generated by Django 4.1.4 on 2023-04-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
